name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/receiptsnap-backend:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            IMAGE=${{ secrets.DOCKER_USERNAME }}/receiptsnap-backend:latest
            sudo apt update && sudo apt install -y docker.io
            sudo systemctl enable docker
            sudo systemctl start docker
            sudo docker pull $IMAGE
            sudo docker stop receiptsnap-backend || true
            sudo docker rm receiptsnap-backend || true
            sudo docker run -d --name receiptsnap-backend -p 3000:3000 --env-file /var/www/receiptsnap-backend/.env $IMAGE
